### PR TITLE
Provide named exports, fixes #27

### LINKED ISSUE #27: Named exports instead of default export?
For better tree-shaking.

### PR DESCRIPTION
**Pull request by broofa**
[Deleted previous description.]

Adds support for named exports.  This is achieved by declaring all functions and constants as named exports, first, and then using them to compose the default object API.

All that other guff about `ava` and `xo`, etc... has been reverted. 😄 

Fixes #27

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's generally best to focus on the issue at hand and not cramp in lots of unrelated changes. I'm using XO and AVA in all my projects and I don't plan to remove them here. I also prefer keeping the default export to not break backwards compatibility, but also because I think it's a better API.

**Comment by broofa** [comment]
@sindresorhus :  Reverted all changes not essential to #27 .   If you could take another look, that'd be great.  If you're still not interested, go ahead and close I suppose.  Cheers!

**Comment by sindresorhus** [comment]
You can use this trick to avoid having to specify the named exports manually for the default export: https://github.com/sindresorhus/query-string/blob/main/index.js

**Comment by sindresorhus** [comment]
> You can use this trick to avoid having to specify the named exports manually for the default export: [sindresorhus/query-string@main/index.js](https://github.com/sindresorhus/query-string/blob/main/index.js?rgh-link-date=2024-04-27T05%3A44%3A54Z)

Also for index.d.ts

**Comment by broofa** [comment]
@sindresorhus Updated the *.d.ts file to use the same index/base pattern.  Note that this uses the "`export * as default from '...'`" pattern for the default export in `index.d.ts`.  This was the only pattern that seemed to keep both TypeScript (in VSCode) from complaining, and also satisfy `tsd` in the unit test.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
